# Generated by Django 5.0.6 on 2024-06-12 07:50

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='ALTER TABLE todos_todo RENAME COLUMN "Category_id" TO "category_id";',
            reverse_sql='ALTER TABLE todos_todo RENAME COLUMN "category_id" TO "Category_id";',
        ),
    ]

